AWSTemplateFormatVersion: "2010-09-09"
Description:  "This is my first template"
Resources:
  # Security Group Creation
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"  # Allow SSH from anywhere  
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-075449515af5df0d1
      KeyName: !Ref MyKeyPair
      SecurityGroups:
        - !Ref MySecurityGroup
      InstanceType: t2.micro
